version: "3.3"

services:
  bookmarks-backend:
    build:
      context: ./
      dockerfile: Dockerfile
      target: install
    command: /bin/sh -c 'npm install && npm run dev'
    container_name: bookmarks-backend
    environment:
      - NODE_ENV=development
      - DOCKER=true
    ports:
      - 9001:9001
      - 9229:9229
    networks:
      - bookmarks-net
    volumes:
      - type: bind
        source: ./
        target: /home/node/bookmarks-backend
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=bookmarks-development
    ports:
      - 5432:5432
    networks:
      - bookmarks-net
    volumes:
      - type: volume
        source: bookmarks-backend-postgres-vol
        target: /var/lib/postgresql/data

networks:
  bookmarks-net:

volumes:
  bookmarks-backend-postgres:
