version: "3.3"

services:
  bookmarks-backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: bookmarks-backend
    environment:
      - NODE_ENV=development
      - DOCKER=true
    ports:
      - 9001:9001
    networks:
      - bookmarks-net
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    container_name: bookmarks-backend-mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27017:27017
    networks:
      - bookmarks-net
    volumes:
      - type: volume
        source: bookmarks-backend-mongo
        target: /data/db

networks:
  bookmarks-net:

volumes:
  bookmarks-backend-mongo:
