version: '3'
services:
  bookmarks-api:
    build: .
    restart: always
    environment:
      - NODE_ENV=$NODE_ENV
      - DATABASE_URI=$DATABASE_URI
      - JWT_SECRET=$JWT_SECRET
    ports:
      - $PORTS:8000
