version: "3.4"

services:
  bookmarks-backend:
    depends_on:
      - mongo
    container_name: bookmarks-backend
    build:
      context: ./
      dockerfile: Dockerfile
      target: install
    env_file:
      - .env.development
    environment:
      - MONGO_URI=mongodb://bookmarks-backend-mongo:27017
    ports:
      - ${PORT:-9001}:${PORT:-9001}
    command: ["npm", "run", "dev"]
    volumes:
      - .:/home/node/bookmarks-backend
      - /home/node/bookmarks-backend/node_modules
    networks:
      - bookmarks-net
  mongo:
    image: mongo:latest
    container_name: bookmarks-backend-mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - bookmarks-net
    volumes:
      - type: volume
        source: bookmarks-backend-mongo
        target: /data/db

networks:
  bookmarks-net:

volumes:
  bookmarks-backend-mongo:
