version: '3'

services:
  bookmarks-backend:
    environment:
      - NODE_ENV=development
      - JWT_SECRET=secret
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: bookmarks-backend
    volumes:
      - ./:/home/node/bookmarks-backend
    ports:
      - 5000:5000
      - 9229:9229
    command: /bin/sh -c 'yarn install && yarn run debug'
